name: Build and deploy to Heroku

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
        env:
          VITE_USERNAME: ${{ secrets.VITE_USERNAME }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_SECRET_ID: ${{ secrets.VITE_SECRET_ID }}
          VITE_SECRET_VALUE: ${{ secrets.VITE_SECRET_VALUE }}
          VITE_SERVER: ${{ secrets.VITE_SERVER }}
          VITE_SITE: ${{ secrets.VITE_SITE }}
          VITE_SUBSCRIBER: ${{ secrets.VITE_SUBSCRIBER }}
          VITE_DATASOURCE_LUID: ${{ secrets.VITE_DATASOURCE_LUID }}
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "ebikes-demo"
          DEPLOY_PATH: "../deploy-demo"
        run: |
          rm -rf $DEPLOY_PATH
          mkdir $DEPLOY_PATH
          mkdir $DEPLOY_PATH/src
          mkdir $DEPLOY_PATH/src/client
          mkdir $DEPLOY_PATH/src/db
          mkdir $DEPLOY_PATH/src/server
          mv prod-package.json $DEPLOY_PATH/package.json
          rm -rf dist/data
          cp -a dist/. $DEPLOY_PATH/dist
          cp -a src/client/. $DEPLOY_PATH/src/client
          cp -a src/db/. $DEPLOY_PATH/src/db
          cp -a src/server/. $DEPLOY_PATH/src/server
          cd $DEPLOY_PATH
          git init
          git config --global user.email "devplat.heroku@salesforce.com"
          git config --global user.name "DevPlat Heroku"
          git add .
          git commit -m "Production deploy commit"
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
          git push -f heroku HEAD:master
